apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  selector:
    matchLabels:
      app: webapp2
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
        ports:
         -  containerPort: 80